// Generated from _00_themes.sass by scripts/update-registry.js — do not edit.
export interface ThemeMeta {
	id: string;
	mode: 'light' | 'dark';
	/** The same palette in the opposite mode, when one exists. */
	twin?: string;
}

/** The 76 built-in palettes. Apply with setTheme(id).  */
export const themes: readonly ThemeMeta[] = [
	{ id: 'theme-light-default', mode: 'light', twin: 'theme-dark-default' },
	{ id: 'theme-himalaya-light', mode: 'light', twin: 'theme-himalaya-dark' },
	{ id: 'theme-editorial-light', mode: 'light', twin: 'theme-editorial-dark' },
	{ id: 'theme-space-light', mode: 'light', twin: 'theme-space-dark' },
	{ id: 'theme-sun-light', mode: 'light', twin: 'theme-sun-dark' },
	{ id: 'theme-monochrono-light', mode: 'light', twin: 'theme-monochrono-dark' },
	{ id: 'theme-molly-light', mode: 'light', twin: 'theme-molly-dark' },
	{ id: 'theme-malana-light', mode: 'light', twin: 'theme-malana-dark' },
	{ id: 'theme-coresync-light', mode: 'light', twin: 'theme-coresync-dark' },
	{ id: 'theme-studio-light', mode: 'light', twin: 'theme-studio-dark' },
	{ id: 'theme-matcha-light', mode: 'light', twin: 'theme-matcha-dark' },
	{ id: 'theme-sakura-light', mode: 'light', twin: 'theme-sakura-dark' },
	{ id: 'theme-nordic-frost-light', mode: 'light', twin: 'theme-nordic-frost-dark' },
	{ id: 'theme-desert-dune-light', mode: 'light', twin: 'theme-desert-dune-dark' },
	{ id: 'theme-lavender-mist-light', mode: 'light', twin: 'theme-lavender-mist-dark' },
	{ id: 'theme-botanical-light', mode: 'light', twin: 'theme-botanical-dark' },
	{ id: 'theme-clay-studio-light', mode: 'light', twin: 'theme-clay-studio-dark' },
	{ id: 'theme-solaris-light', mode: 'light', twin: 'theme-solaris-dark' },
	{ id: 'theme-cyberpunk-day-light', mode: 'light', twin: 'theme-cyberpunk-day-dark' },
	{ id: 'theme-copper-patina-light', mode: 'light', twin: 'theme-copper-patina-dark' },
	{ id: 'theme-dracula-light', mode: 'light', twin: 'theme-dracula-dark' },
	{ id: 'theme-lagoona-dark', mode: 'dark', twin: 'theme-lagoona-light' },
	{ id: 'theme-frozen-dark', mode: 'dark', twin: 'theme-frozen-light' },
	{ id: 'theme-night-dark', mode: 'dark', twin: 'theme-night-light' },
	{ id: 'theme-inkworm-dark', mode: 'dark', twin: 'theme-inkworm-light' },
	{ id: 'theme-monochrono-dark', mode: 'dark', twin: 'theme-monochrono-light' },
	{ id: 'theme-fouram-dark', mode: 'dark', twin: 'theme-fouram-light' },
	{ id: 'theme-wintercame-dark', mode: 'dark', twin: 'theme-wintercame-light' },
	{ id: 'theme-sun-dark', mode: 'dark', twin: 'theme-sun-light' },
	{ id: 'theme-console-dark', mode: 'dark', twin: 'theme-console-light' },
	{ id: 'theme-dracula-dark', mode: 'dark', twin: 'theme-dracula-light' },
	{ id: 'theme-catppuccin-mocha', mode: 'dark', twin: 'theme-catppuccin-latte' },
	{ id: 'theme-nord-dark', mode: 'dark', twin: 'theme-nord-light' },
	{ id: 'theme-gruvbox-dark', mode: 'dark', twin: 'theme-gruvbox-light' },
	{ id: 'theme-onedark-pro', mode: 'dark', twin: 'theme-onelight-pro' },
	{ id: 'theme-rose-pine-dark', mode: 'dark', twin: 'theme-rose-pine-light' },
	{ id: 'theme-midnight-emerald-dark', mode: 'dark', twin: 'theme-midnight-emerald-light' },
	{ id: 'theme-obsidian-crimson-dark', mode: 'dark', twin: 'theme-obsidian-crimson-light' },
	{ id: 'theme-synthwave-dark', mode: 'dark', twin: 'theme-synthwave-light' },
	{ id: 'theme-deep-ocean-dark', mode: 'dark', twin: 'theme-deep-ocean-light' },
	{ id: 'theme-amethyst-void-dark', mode: 'dark', twin: 'theme-amethyst-void-light' },
	{ id: 'theme-dark-default', mode: 'dark', twin: 'theme-light-default' },
	{ id: 'theme-himalaya-dark', mode: 'dark', twin: 'theme-himalaya-light' },
	{ id: 'theme-editorial-dark', mode: 'dark', twin: 'theme-editorial-light' },
	{ id: 'theme-space-dark', mode: 'dark', twin: 'theme-space-light' },
	{ id: 'theme-molly-dark', mode: 'dark', twin: 'theme-molly-light' },
	{ id: 'theme-malana-dark', mode: 'dark', twin: 'theme-malana-light' },
	{ id: 'theme-coresync-dark', mode: 'dark', twin: 'theme-coresync-light' },
	{ id: 'theme-studio-dark', mode: 'dark', twin: 'theme-studio-light' },
	{ id: 'theme-matcha-dark', mode: 'dark', twin: 'theme-matcha-light' },
	{ id: 'theme-sakura-dark', mode: 'dark', twin: 'theme-sakura-light' },
	{ id: 'theme-nordic-frost-dark', mode: 'dark', twin: 'theme-nordic-frost-light' },
	{ id: 'theme-desert-dune-dark', mode: 'dark', twin: 'theme-desert-dune-light' },
	{ id: 'theme-lavender-mist-dark', mode: 'dark', twin: 'theme-lavender-mist-light' },
	{ id: 'theme-botanical-dark', mode: 'dark', twin: 'theme-botanical-light' },
	{ id: 'theme-clay-studio-dark', mode: 'dark', twin: 'theme-clay-studio-light' },
	{ id: 'theme-solaris-dark', mode: 'dark', twin: 'theme-solaris-light' },
	{ id: 'theme-cyberpunk-day-dark', mode: 'dark', twin: 'theme-cyberpunk-day-light' },
	{ id: 'theme-copper-patina-dark', mode: 'dark', twin: 'theme-copper-patina-light' },
	{ id: 'theme-lagoona-light', mode: 'light', twin: 'theme-lagoona-dark' },
	{ id: 'theme-frozen-light', mode: 'light', twin: 'theme-frozen-dark' },
	{ id: 'theme-night-light', mode: 'light', twin: 'theme-night-dark' },
	{ id: 'theme-inkworm-light', mode: 'light', twin: 'theme-inkworm-dark' },
	{ id: 'theme-fouram-light', mode: 'light', twin: 'theme-fouram-dark' },
	{ id: 'theme-wintercame-light', mode: 'light', twin: 'theme-wintercame-dark' },
	{ id: 'theme-console-light', mode: 'light', twin: 'theme-console-dark' },
	{ id: 'theme-catppuccin-latte', mode: 'light', twin: 'theme-catppuccin-mocha' },
	{ id: 'theme-nord-light', mode: 'light', twin: 'theme-nord-dark' },
	{ id: 'theme-gruvbox-light', mode: 'light', twin: 'theme-gruvbox-dark' },
	{ id: 'theme-onelight-pro', mode: 'light', twin: 'theme-onedark-pro' },
	{ id: 'theme-rose-pine-light', mode: 'light', twin: 'theme-rose-pine-dark' },
	{ id: 'theme-midnight-emerald-light', mode: 'light', twin: 'theme-midnight-emerald-dark' },
	{ id: 'theme-obsidian-crimson-light', mode: 'light', twin: 'theme-obsidian-crimson-dark' },
	{ id: 'theme-synthwave-light', mode: 'light', twin: 'theme-synthwave-dark' },
	{ id: 'theme-deep-ocean-light', mode: 'light', twin: 'theme-deep-ocean-dark' },
	{ id: 'theme-amethyst-void-light', mode: 'light', twin: 'theme-amethyst-void-dark' }
] as const;

export const themeIds: readonly string[] = themes.map((t) => t.id);
