// Writes the missing counterpart for every unpaired palette into
// _00_themes.sass. Idempotent: skips any family that is already paired.
import fs from 'node:fs';
import path from 'node:path';
import { counterpart, contrast } from './pair-themes.mjs';

const FILE = path.join(process.cwd(), 'src/lib/styles/_00_themes.sass');
const src = fs.readFileSync(FILE, 'utf8');

const TOKEN_ORDER = [
	'--bg','--bg-surface','--bg-raised','--bg-panel','--bg-footer','--bg-popover',
	'--bg-dialog','--bg-terminal','--bg-input','--bg-canvas','--border','--border-subtle',
	'--text-primary','--text-secondary','--text-muted','--state-hover','--state-hover-subtle',
	'--state-selected','--theme-color','--theme-color-alt','--text-inverse','--feedback-error'
];

// Palettes whose id carries no -light/-dark suffix. Their counterparts take the
// upstream project's own name for the other mode rather than a bolted-on suffix.
const EXPLICIT = {
	'theme-light-default': { twin: 'theme-dark-default', mode: 'dark' },
	'theme-catppuccin-mocha': { twin: 'theme-catppuccin-latte', mode: 'light' },
	'theme-onedark-pro': { twin: 'theme-onelight-pro', mode: 'light' }
};

const blocks = {}; const order = []; let cur = null;
for (const line of src.split('\n')) {
	const m = line.match(/^\.(theme-[\w-]+)/);
	if (m) { cur = m[1]; blocks[cur] = {}; order.push(cur); continue; }
	const t = line.match(/^\t(--[\w-]+):\s*(\S+)/);
	if (t && cur) blocks[cur][t[1]] = t[2];
}

function twinNameOf(id) {
	if (EXPLICIT[id]) return EXPLICIT[id];
	const base = id.replace(/-(light|dark)$/, '');
	if (base === id) return null;
	const mode = id.endsWith('-light') ? 'dark' : 'light';
	return { twin: `${base}-${mode}`, mode };
}

const additions = [];
const report = [];
for (const id of order) {
	const t = twinNameOf(id);
	if (!t || blocks[t.twin]) continue;                 // already paired (or hand-written)
	if (additions.some((a) => a.id === t.twin)) continue;
	const gen = counterpart(blocks[id], t.mode);
	additions.push({ id: t.twin, from: id, mode: t.mode, tokens: gen });
	report.push({
		id: t.twin,
		primary: contrast(gen['--text-primary'], gen['--bg']),
		secondary: contrast(gen['--text-secondary'], gen['--bg']),
		muted: contrast(gen['--text-muted'], gen['--bg']),
		accent: contrast(gen['--theme-color'], gen['--bg'])
	});
}

const body = additions
	.map((a) => {
		const lines = TOKEN_ORDER.map((k) => `\t${k}: ${a.tokens[k]}`).join('\n');
		return `// ${a.id.replace('theme-', '')} — counterpart of ${a.id === EXPLICIT[a.from]?.twin ? a.from : a.from}\n// twin: ${a.from}\n.${a.id}\n${lines}`;
	})
	.join('\n\n');

const header = `\n\n// ============================================================================\n// PAIRED COUNTERPARTS (${additions.length})\n//\n// Generated by scripts/generate-pairs.mjs from the palette named in each\n// \`// twin:\` line. The lightness ramp is measured from the three families that\n// were paired by hand — sun, monochrono, dracula — so a counterpart keeps its\n// source palette's hue and chroma and only moves through the ramp.\n//\n// Accents keep their hue. sun and monochrono flip theirs ~180deg by hand; two\n// of three families disagreeing is not a rule, so identity wins over imitation.\n//\n// \`pnpm pair\` only ADDS counterparts that are missing — it never rewrites an\n// existing block, so hand-edits here are safe. To regenerate one, delete its\n// block and re-run.\n// ============================================================================\n\n`;

fs.writeFileSync(FILE, src.replace(/\s*$/, '') + header + body + '\n', 'utf8');

console.log(`✔ wrote ${additions.length} counterparts\n`);
const bad = report.filter((r) => r.primary < 7 || r.secondary < 4.5 || r.accent < 3);
console.log(`contrast — primary >=7 : ${report.filter((r) => r.primary >= 7).length}/${report.length}`);
console.log(`           secondary >=4.5 : ${report.filter((r) => r.secondary >= 4.5).length}/${report.length}`);
console.log(`           accent >=3 : ${report.filter((r) => r.accent >= 3).length}/${report.length}`);
console.log(`           muted >=3 : ${report.filter((r) => r.muted >= 3).length}/${report.length}`);
if (bad.length) {
	console.log('\nbelow target:');
	for (const b of bad) console.log(`  ${b.id.padEnd(32)} primary ${b.primary.toFixed(2)} secondary ${b.secondary.toFixed(2)} accent ${b.accent.toFixed(2)}`);
}
